export default function getRoutes() {
  const extra = JSON.parse(process.env.EXTRA_ROUTES || '{}').routes || [];
  return [
    {
      path: '/user',
      layout: false,
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: './User/Login',
        },
        {
          name: 'register',
          path: '/user/register',
          component: './User/Register',
        },
        {
          name: 'forgotPassword',
          path: '/user/forgot-password',
          component: './User/ForgotPassword',
        },
        {
          name: 'consent',
          path: '/user/consent',
          component: './User/Consent',
        },
        {
          name: 'logout',
          path: '/user/logout',
          component: './User/Logout',
        },
        {
          component: './404',
        },
      ],
    },
    {
      path: '/password/reset',
      layout: false,
      hideInMenu: true,
      component: './User/ForgotPassword',
    },
    {
      path: '/password/reset/verify',
      layout: false,
      hideInMenu: true,
      component: './User/PasswordResetVerify',
    },
    {
      path: '/password/reset/verify/:token/:email',
      layout: false,
      hideInMenu: true,
      component: './User/PasswordResetVerify',
    },
    {
      path: '/password/reset/verify/:email',
      layout: false,
      hideInMenu: true,
      component: './User/PasswordResetVerify',
    },
    {
      path: '/password/reset/update/:token',
      layout: false,
      hideInMenu: true,
      component: './User/PasswordReset',
    },
    {
      path: '/all-alumni',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/alumni/profile/:id',
      layout: false,
      hideInMenu: true,
      component: './Public/AlumniProfile',
    },
    {
      path: '/all-event',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/event-view-details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentDetail',
    },
    {
      path: '/our-news',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/all-news',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/news-view-details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentDetail',
    },
    {
      path: '/news-details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentDetail',
    },
    {
      path: '/our-notice',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/all-notice',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/notice-view-details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentDetail',
    },
    {
      path: '/notice-details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentDetail',
    },
    {
      path: '/all-membership',
      layout: false,
      hideInMenu: true,
      component: './Public/Membership',
    },
    {
      path: '/membership-package',
      layout: false,
      hideInMenu: true,
      component: './Public/Membership',
    },
    {
      path: '/all-job',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/job-view-details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentDetail',
    },
    {
      path: '/job-post/create',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/job-post/all-job-post',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/job-post/my-job-post',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/job-post/pending-job-post',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/job-post/details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/all-stories',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentList',
    },
    {
      path: '/view-stories/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/ContentDetail',
    },
    {
      path: '/stories/create',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/stories/list',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/stories/pending',
      layout: false,
      hideInMenu: true,
      component: './Public/StoryJobManage',
    },
    {
      path: '/page/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/Page',
    },
    {
      path: '/contact-us',
      layout: false,
      hideInMenu: true,
      component: './Public/Contact',
    },
    {
      path: '/home',
      layout: false,
      hideInMenu: true,
      component: './Public/AlumniDashboard',
    },
    {
      path: '/dashboard',
      layout: false,
      hideInMenu: true,
      component: './Public/AlumniDashboard',
    },
    {
      path: '/settings',
      layout: false,
      hideInMenu: true,
      component: './Public/AlumniSettings',
    },
    {
      path: '/event/my-ticket',
      layout: false,
      hideInMenu: true,
      component: './Public/EventTickets',
    },
    {
      path: '/event/create',
      layout: false,
      hideInMenu: true,
      component: './Public/EventManage',
    },
    {
      path: '/event/edit/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/EventManage',
    },
    {
      path: '/event/all-event',
      layout: false,
      hideInMenu: true,
      component: './Public/EventManage',
    },
    {
      path: '/event/my-event',
      layout: false,
      hideInMenu: true,
      component: './Public/EventManage',
    },
    {
      path: '/event/pending',
      layout: false,
      hideInMenu: true,
      component: './Public/EventManage',
    },
    {
      path: '/event/category',
      layout: false,
      hideInMenu: true,
      component: './Public/EventCategory',
    },
    {
      path: '/event/details/:slug',
      layout: false,
      hideInMenu: true,
      component: './Public/EventDetail',
    },
    {
      path: '/event/single-ticket/:id',
      layout: false,
      hideInMenu: true,
      component: './Public/EventTicketDetail',
    },
    {
      path: '/email/verify/:token',
      layout: false,
      hideInMenu: true,
      component: './Public/EmailVerify',
    },
    {
      path: '/checkout',
      layout: false,
      hideInMenu: true,
      component: './Public/Checkout',
    },
    {
      path: '/checkout/success',
      layout: false,
      hideInMenu: true,
      component: './Public/CheckoutSuccess',
    },
    {
      path: '/subscription',
      layout: false,
      hideInMenu: true,
      component: './Public/Subscription',
    },
    {
      path: '/subscription/checkout',
      layout: false,
      hideInMenu: true,
      component: './Public/Checkout',
    },
    {
      path: '/subscription/checkout/success',
      layout: false,
      hideInMenu: true,
      component: './Public/CheckoutSuccess',
    },
    {
      path: '/subscription/transaction-list',
      layout: false,
      hideInMenu: true,
      component: './Public/SubscriptionTransactions',
    },
    {
      path: '/chats',
      layout: false,
      hideInMenu: true,
      component: './Public/Chats',
    },
    {
      path: '/transactions',
      layout: false,
      hideInMenu: true,
      component: './Public/Transactions',
    },
    {
      path: '/transactions-download/:id',
      layout: false,
      hideInMenu: true,
      component: './Public/TransactionReceipt',
    },
    {
      path: '/transactions-print/:id',
      layout: false,
      hideInMenu: true,
      component: './Public/TransactionReceipt',
    },
    {
      path: '/admin',
      locale: 'admin.title',
      name: 'admin',
      icon: 'smile',
      routes: [
        {
          name: 'dashboard',
          path: '/admin/dashboard',
          component: './Admin/Dashboard',
        },
        {
          name: 'profile',
          path: '/admin/profile',
          hideInMenu: true,
          component: './Admin/Profile',
        },
        {
          name: 'profileChangePassword',
          path: '/admin/profile/change-password',
          hideInMenu: true,
          component: './Admin/Profile',
        },
        {
          name: 'user',
          path: '/admin/users',
          component: './Admin/User',
        },
        {
          name: 'alumni',
          path: '/admin/alumni/list-search-with-filter',
          component: './Admin/Alumni',
        },
        {
          name: 'alumniPending',
          path: '/admin/alumni/list-pending-alumni-with-filter',
          hideInMenu: true,
          component: './Admin/Alumni',
        },
        {
          name: 'alumniProfileEdit',
          path: '/admin/alumni/alumni-profile-edit/:id',
          hideInMenu: true,
          component: './Admin/AlumniProfileEdit',
        },
        {
          name: 'generalSettings',
          path: '/admin/setting/application-settings',
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsConfiguration',
          path: '/admin/setting/configuration-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsConfigurationConfigure',
          path: '/admin/setting/configuration-settings/configure',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsConfigurationHelp',
          path: '/admin/setting/configuration-settings/help',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsLogo',
          path: '/admin/setting/logo-settings',
          hideInMenu: true,
          component: './Admin/LogoSettings',
        },
        {
          name: 'generalSettingsColor',
          path: '/admin/setting/color-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsRegistrationForm',
          path: '/admin/setting/registration-form-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsStorage',
          path: '/admin/setting/storage-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          path: '/admin/setting/storage-link',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsRecaptcha',
          path: '/admin/setting/google-recaptcha-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsAnalytics',
          path: '/admin/setting/google-analytics-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsMail',
          path: '/admin/setting/mail-configuration',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsSms',
          path: '/admin/setting/sms-configuration',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsMaintenance',
          path: '/admin/setting/maintenance-mode-changes',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsCache',
          path: '/admin/setting/cache-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          path: '/admin/setting/cache-update/:id',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsSecurity',
          path: '/admin/setting/security-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsCookie',
          path: '/admin/setting/cookie-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsLiveChat',
          path: '/admin/setting/live-chat-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsEmailTemplate',
          path: '/admin/setting/email-template',
          hideInMenu: true,
          component: './Admin/EmailTemplates',
        },
        {
          name: 'generalSettingsEmailEdit',
          path: '/admin/setting/email-edit',
          hideInMenu: true,
          component: './Admin/EmailTemplates',
        },
        {
          name: 'generalSettingsEmailEditItem',
          path: '/admin/setting/email-edit/:id',
          hideInMenu: true,
          component: './Admin/EmailTemplates',
        },
        {
          name: 'generalSettingsWebsite',
          path: '/admin/setting/website-settings',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsiteBanner',
          path: '/admin/setting/website-settings/banner-setting',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsiteJoin',
          path: '/admin/setting/website-settings/why-you-should-join-us',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsiteAbout',
          path: '/admin/setting/website-settings/about-us',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsitePrivacy',
          path: '/admin/setting/website-settings/privacy-policy',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsiteCookie',
          path: '/admin/setting/website-settings/cookie-policy',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsiteTerms',
          path: '/admin/setting/website-settings/terms-condition',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsiteRefund',
          path: '/admin/setting/website-settings/refund-policy',
          hideInMenu: true,
          component: './Admin/GeneralSettings',
        },
        {
          name: 'generalSettingsWebsiteContact',
          path: '/admin/setting/website-settings/contact-us',
          hideInMenu: true,
          component: './Admin/ContactMessages',
        },
        {
          name: 'language',
          path: '/admin/setting/language',
          component: './Admin/Language',
        },
        {
          path: '/admin/setting/language/edit/:id',
          hideInMenu: true,
          component: './Admin/Language',
        },
        {
          path: '/admin/setting/language/edit/:id/:isoCode',
          hideInMenu: true,
          component: './Admin/Language',
        },
        {
          name: 'languageTranslate',
          path: '/admin/setting/language/translate/:id',
          hideInMenu: true,
          component: './Admin/Language',
        },
        {
          path: '/admin/setting/language/translate/:id/:isoCode',
          hideInMenu: true,
          component: './Admin/Language',
        },
        {
          name: 'gallery',
          path: '/admin/setting/website-settings/image-galleries',
          component: './Admin/Gallery',
        },
        {
          name: 'galleryEdit',
          path: '/admin/setting/website-settings/image-galleries/edit/:id',
          hideInMenu: true,
          component: './Admin/Gallery',
        },
        {
          name: 'applicationSettings',
          path: '/admin/setting/batch',
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'applicationSettingsBatchEdit',
          path: '/admin/setting/batch/edit/:id',
          hideInMenu: true,
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'applicationSettingsDepartment',
          path: '/admin/setting/department',
          hideInMenu: true,
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'applicationSettingsDepartmentEdit',
          path: '/admin/setting/department/edit/:id',
          hideInMenu: true,
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'applicationSettingsPassingYears',
          path: '/admin/setting/passing-years',
          hideInMenu: true,
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'applicationSettingsPassingYearsEdit',
          path: '/admin/setting/passing-years/edit/:id',
          hideInMenu: true,
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'currency',
          path: '/admin/setting/currency',
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'currencyEdit',
          path: '/admin/setting/currency/edit/:id',
          hideInMenu: true,
          component: './Admin/ApplicationSettings',
        },
        {
          name: 'gateway',
          path: '/admin/setting/gateway',
          component: './Admin/Gateway',
        },
        {
          path: '/admin/setting/gateway/get-info',
          hideInMenu: true,
          component: './Admin/Gateway',
        },
        {
          path: '/admin/setting/gateway/get-currency-by-gateway',
          hideInMenu: true,
          component: './Admin/Gateway',
        },
        {
          path: '/admin/setting/gateway/syncs',
          hideInMenu: true,
          component: './Admin/Gateway',
        },
        {
          name: 'transactions',
          path: '/admin/transactions/pending-list',
          component: './Admin/Transactions',
        },
        {
          name: 'transactionsAll',
          path: '/admin/transactions/all-transactions',
          hideInMenu: true,
          component: './Admin/Transactions',
        },
        {
          name: 'transactionsEvent',
          path: '/admin/transactions/event-transaction',
          hideInMenu: true,
          component: './Admin/Transactions',
        },
        {
          name: 'transactionsMembership',
          path: '/admin/transactions/membership-transaction',
          hideInMenu: true,
          component: './Admin/Transactions',
        },
        {
          name: 'customDomain',
          path: '/admin/custom-domain',
          component: './Admin/CustomDomain',
        },
        {
          path: '/admin/custom-domain/info/:id',
          hideInMenu: true,
          component: './Admin/CustomDomain',
        },
        {
          name: 'versionUpdate',
          path: '/admin/version-update',
          component: './Admin/VersionUpdate',
        },
        {
          path: '/admin/version-update-execute',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          path: '/admin/version-delete',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          name: 'addonDetails',
          path: '/admin/addon/details/:id',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          path: '/admin/addon/delete/:id',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          name: 'newsletter',
          path: '/admin/news-subscription-letter-email',
          component: './Admin/Newsletter',
        },
        {
          name: 'newsletterEdit',
          path: '/admin/news-subscription-letter-email/edit/:id',
          hideInMenu: true,
          component: './Admin/Newsletter',
        },
        {
          name: 'newsletterTemplates',
          path: '/admin/subscription-email-template',
          hideInMenu: true,
          component: './Admin/Newsletter',
        },
        {
          name: 'newsletterTemplatesEdit',
          path: '/admin/subscription-email-template/edit/:id',
          hideInMenu: true,
          component: './Admin/Newsletter',
        },
        {
          name: 'newsletterTemplatesView',
          path: '/admin/subscription-email-template/view/:id',
          hideInMenu: true,
          component: './Admin/Newsletter',
        },
        {
          name: 'newsletterSendMail',
          path: '/admin/subscription-email-template/send-mail-list',
          hideInMenu: true,
          component: './Admin/Newsletter',
        },
        {
          name: 'subscription',
          path: '/admin/subscription',
          component: './Admin/Subscription',
        },
        {
          name: 'subscriptionCheckout',
          path: '/admin/subscription/checkout',
          hideInMenu: true,
          component: './Admin/Subscription',
        },
        {
          name: 'subscriptionCheckoutSuccess',
          path: '/admin/subscription/checkout/success',
          hideInMenu: true,
          component: './Admin/Subscription',
        },
        {
          path: '/admin/subscription/get-package',
          hideInMenu: true,
          component: './Admin/Subscription',
        },
        {
          path: '/admin/subscription/get-currency-by-gateway',
          hideInMenu: true,
          component: './Admin/Subscription',
        },
        {
          name: 'subscriptionTransactions',
          path: '/admin/subscription/transaction-list',
          hideInMenu: true,
          component: './Admin/Subscription',
        },
        {
          name: 'news',
          path: '/admin/news/list',
          component: './Admin/NewsNotice',
        },
        {
          path: '/admin/news/info/:id',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          name: 'newsCategories',
          path: '/admin/news/categories/list',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          path: '/admin/news/categories/info/:id',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          name: 'newsTags',
          path: '/admin/news/tags/list',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          path: '/admin/news/tags/info/:id',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          name: 'notices',
          path: '/admin/notices/list',
          component: './Admin/NewsNotice',
        },
        {
          path: '/admin/notices/info/:id',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          name: 'noticeCategories',
          path: '/admin/notices/categories/list',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          path: '/admin/notices/categories/info/:id',
          hideInMenu: true,
          component: './Admin/NewsNotice',
        },
        {
          name: 'events',
          path: '/admin/event/pending',
          component: './Admin/Events',
        },
        {
          name: 'eventCategories',
          path: '/admin/event/category',
          hideInMenu: true,
          component: './Admin/EventCategories',
        },
        {
          path: '/admin/event/info/:id',
          hideInMenu: true,
          component: './Admin/EventCategories',
        },
        {
          name: 'jobPosts',
          path: '/admin/job-post/pending-job-post',
          component: './Admin/JobPosts',
        },
        {
          path: '/admin/job-post/info/:slug',
          hideInMenu: true,
          component: './Admin/JobPosts',
        },
        {
          name: 'stories',
          path: '/admin/stories/pending',
          component: './Admin/Stories',
        },
        {
          name: 'moderators',
          path: '/admin/moderators',
          component: './Admin/Moderators',
        },
        {
          name: 'moderatorsEdit',
          path: '/admin/moderators/edit/:id',
          hideInMenu: true,
          component: './Admin/Moderators',
        },
        {
          name: 'roles',
          path: '/admin/roles',
          component: './Admin/Roles',
        },
        {
          name: 'rolesEdit',
          path: '/admin/roles/edit/:id',
          hideInMenu: true,
          component: './Admin/Roles',
        },
        {
          name: 'membership',
          path: '/admin/membership/index',
          component: './Admin/Membership',
        },
        {
          name: 'membershipMembers',
          path: '/admin/membership/list',
          hideInMenu: true,
          component: './Admin/Membership',
        },
        {
          name: 'membershipEdit',
          path: '/admin/membership/edit/:slug',
          hideInMenu: true,
          component: './Admin/Membership',
        },
      ],
    },
    {
      path: '/super-admin',
      locale: 'superAdmin.title',
      name: 'superAdmin',
      icon: 'dashboard',
      routes: [
        {
          name: 'dashboard',
          path: '/super-admin/dashboard',
          component: './SuperAdmin/Dashboard',
        },
        {
          name: 'versionUpdate',
          path: '/super-admin/version-update',
          component: './Admin/VersionUpdate',
        },
        {
          path: '/super-admin/version-update-execute',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          path: '/super-admin/version-delete',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          name: 'addonDetails',
          path: '/super-admin/addon/details/:id',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          path: '/super-admin/addon/delete/:id',
          hideInMenu: true,
          component: './Admin/VersionUpdate',
        },
        {
          name: 'profile',
          path: '/super-admin/profile',
          hideInMenu: true,
          component: './SuperAdmin/Profile',
        },
        {
          name: 'profileChangePassword',
          path: '/super-admin/profile/change-password',
          hideInMenu: true,
          component: './SuperAdmin/Profile',
        },
        {
          name: 'emailTemplates',
          path: '/super-admin/setting/email-template',
          component: './SuperAdmin/EmailTemplates',
        },
        {
          name: 'emailTemplateConfig',
          path: '/super-admin/setting/email-template-config',
          hideInMenu: true,
          component: './SuperAdmin/EmailTemplates',
        },
        {
          name: 'applicationSettings',
          path: '/super-admin/setting/application-settings',
          component: './SuperAdmin/ApplicationSettings',
        },
        {
          name: 'configurationSettings',
          path: '/super-admin/setting/configuration-settings',
          component: './SuperAdmin/ConfigurationSettings',
        },
        {
          name: 'configurationSettingsConfigure',
          path: '/super-admin/setting/configuration-settings/configure',
          hideInMenu: true,
          component: './SuperAdmin/ConfigurationSettings',
        },
        {
          name: 'configurationSettingsHelp',
          path: '/super-admin/setting/configuration-settings/help',
          hideInMenu: true,
          component: './SuperAdmin/ConfigurationSettings',
        },
        {
          name: 'logoSettings',
          path: '/super-admin/setting/logo-settings',
          component: './SuperAdmin/LogoSettings',
        },
        {
          name: 'operationalSettings',
          path: '/super-admin/setting/storage-settings',
          component: './SuperAdmin/OperationalSettings',
        },
        {
          path: '/super-admin/setting/storage-link',
          hideInMenu: true,
          component: './SuperAdmin/OperationalSettings',
        },
        {
          name: 'operationalSettingsColor',
          path: '/super-admin/setting/color-settings',
          hideInMenu: true,
          component: './SuperAdmin/OperationalSettings',
        },
        {
          name: 'operationalSettingsMail',
          path: '/super-admin/setting/mail-configuration',
          hideInMenu: true,
          component: './SuperAdmin/OperationalSettings',
        },
        {
          name: 'operationalSettingsSms',
          path: '/super-admin/setting/sms-configuration',
          hideInMenu: true,
          component: './SuperAdmin/OperationalSettings',
        },
        {
          name: 'operationalSettingsMaintenance',
          path: '/super-admin/setting/maintenance-mode-changes',
          hideInMenu: true,
          component: './SuperAdmin/OperationalSettings',
        },
        {
          name: 'operationalSettingsCache',
          path: '/super-admin/setting/cache-settings',
          hideInMenu: true,
          component: './SuperAdmin/OperationalSettings',
        },
        {
          path: '/super-admin/setting/cache-update/:id',
          hideInMenu: true,
          component: './SuperAdmin/OperationalSettings',
        },
        {
          name: 'language',
          path: '/super-admin/setting/language',
          component: './SuperAdmin/Language',
        },
        {
          path: '/super-admin/setting/language/edit/:id',
          hideInMenu: true,
          component: './SuperAdmin/Language',
        },
        {
          path: '/super-admin/setting/language/edit/:id/:isoCode',
          hideInMenu: true,
          component: './SuperAdmin/Language',
        },
        {
          name: 'languageTranslate',
          path: '/super-admin/setting/language/translate/:id',
          hideInMenu: true,
          component: './SuperAdmin/Language',
        },
        {
          path: '/super-admin/setting/language/translate/:id/:isoCode',
          hideInMenu: true,
          component: './SuperAdmin/Language',
        },
        {
          name: 'customDomainDetails',
          path: '/super-admin/setting/custom-domain-details',
          component: './SuperAdmin/CustomDomainDetails',
        },
        {
          name: 'currency',
          path: '/super-admin/setting/currency',
          component: './SuperAdmin/Currency',
        },
        {
          name: 'currencyEdit',
          path: '/super-admin/setting/currency/edit/:id',
          hideInMenu: true,
          component: './SuperAdmin/Currency',
        },
        {
          name: 'gateway',
          path: '/super-admin/setting/gateway',
          component: './SuperAdmin/Gateway',
        },
        {
          path: '/super-admin/setting/gateway/get-info',
          hideInMenu: true,
          component: './SuperAdmin/Gateway',
        },
        {
          path: '/super-admin/setting/gateway/get-currency-by-gateway',
          hideInMenu: true,
          component: './SuperAdmin/Gateway',
        },
        {
          path: '/super-admin/setting/gateway/syncs',
          hideInMenu: true,
          component: './SuperAdmin/Gateway',
        },
      ],
    },
    {
      path: '/sys',
      locale: 'sys.title',
      name: 'sys',
      icon: 'smile',
      routes: [
        {
          name: 'user',
          path: '/sys/users',
          component: './Sys/User',
        },
        {
          name: 'role',
          path: '/sys/roles',
          component: './Sys/Role',
        },
        {
          name: 'role-detail',
          path: '/sys/role/:id',
          component: './Sys/RoleDetail',
          hideInMenu: true,
        },
        {
          name: 'menu',
          path: '/sys/menus',
          component: './Sys/Menu',
        },
      ],
    },
    {
      path: '/oidc',
      icon: 'smile',
      routes: [
        {
          path: '/oidc/clients',
          component: './Oidc/Client',
        },
      ],
    },
    {
      path: '/saas',
      name: 'saas',
      icon: 'smile',
      routes: [
        {
          name: 'tenant',
          path: '/saas/tenants',
          component: './Saas/Tenant',
        },
        {
          name: 'plan',
          path: '/saas/plans',
          component: './Saas/Plan',
        },
      ],
    },
    {
      path: '/payment',
      name: 'payment',
      icon: 'smile',
      routes: [
        {
          name: 'payment.orders',
          path: '/payment/orders',
          component: './Order/Order',
        },
        {
          name: 'payment.subscriptions',
          path: '/payment/subscriptions',
          component: './Order/Order',
        },
      ],
    },
    {
      path: '/product',
      name: 'product',
      routes: [
        {
          name: 'product.products',
          path: '/product/products',
          component: './Product/Product',
        },
      ],
    },
    {
      name: 'dashboard',
      icon: 'table',
      routes: [
        {
          name: 'workbench',
          path: '/dashboard/workbench',
          component: './Welcome',
        },
      ],
    },
    ...extra,
    {
      path: '/',
      layout: false,
      hideInMenu: true,
      component: './Public/Home',
    },
    {
      path: '*',
      component: './404',
    },
  ];
}
