import type { ProColumnType } from '@ant-design/pro-components';
import { ProFormSelect, ProFormText } from '@ant-design/pro-components';
import { FormattedMessage, useIntl } from '@umijs/max';
import React, { useEffect, useState } from 'react';
import type {
  V1CreateStudentFeeRequest,
  V1FeeGroup,
  V1FeeMaster,
  V1FeeType,
  V1Student,
  V1StudentFee,
} from '@gosaas/api';
import {
  FeeGroupServiceApi,
  FeeMasterServiceApi,
  FeeTypeServiceApi,
  StudentFeeServiceApi,
  StudentServiceApi,
} from '@gosaas/api';
import ReferencePage from '../../Student/components/ReferencePage';

const service = new StudentFeeServiceApi();
const studentService = new StudentServiceApi();
const feeMasterService = new FeeMasterServiceApi();
const groupService = new FeeGroupServiceApi();
const typeService = new FeeTypeServiceApi();

const keyedById = <T extends { id?: string }>(items: T[] = []) =>
  items.reduce<Record<string, T>>((ret, item) => {
    if (item.id) {
      ret[item.id] = item;
    }
    return ret;
  }, {});

const studentsByEnrollment = (items: V1Student[] = []) =>
  items.reduce<Record<string, V1Student>>((ret, item) => {
    if (item.enrollment?.id) {
      ret[item.enrollment.id] = item;
    }
    return ret;
  }, {});

const studentLabel = (student?: V1Student) => {
  if (!student) {
    return '-';
  }
  return [
    student.admissionNo,
    [student.firstName, student.lastName].filter(Boolean).join(' '),
    student.enrollment?.rollNo,
  ]
    .filter(Boolean)
    .join(' - ');
};

const feeMasterLabel = (
  item: V1FeeMaster | undefined,
  groups: Record<string, V1FeeGroup>,
  types: Record<string, V1FeeType>,
) => {
  if (!item) {
    return '-';
  }
  return [
    groups[item.feeGroupId || '']?.name || item.feeGroupId,
    types[item.feeTypeId || '']?.name || types[item.feeTypeId || '']?.code || item.feeTypeId,
    item.amount ? `BDT ${item.amount}` : undefined,
  ]
    .filter(Boolean)
    .join(' - ');
};

const TableList: React.FC = () => {
  const intl = useIntl();
  const [students, setStudents] = useState<Record<string, V1Student>>({});
  const [feeMasters, setFeeMasters] = useState<Record<string, V1FeeMaster>>({});
  const [groups, setGroups] = useState<Record<string, V1FeeGroup>>({});
  const [types, setTypes] = useState<Record<string, V1FeeType>>({});

  useEffect(() => {
    Promise.all([
      studentService.studentServiceListStudent2({
        body: { pageSize: 200, sort: ['admission_no'] },
      }),
      feeMasterService.feeMasterServiceListFeeMaster2({
        body: { pageSize: 200, sort: ['due_date'] },
      }),
      groupService.feeGroupServiceListFeeGroup2({ body: { pageSize: 200, sort: ['name'] } }),
      typeService.feeTypeServiceListFeeType2({ body: { pageSize: 200, sort: ['code'] } }),
    ]).then(([studentResp, feeResp, groupResp, typeResp]) => {
      setStudents(studentsByEnrollment(studentResp.data.items));
      setFeeMasters(keyedById(feeResp.data.items));
      setGroups(keyedById(groupResp.data.items));
      setTypes(keyedById(typeResp.data.items));
    });
  }, []);

  const columns: ProColumnType<V1StudentFee>[] = [
    {
      title: <FormattedMessage id="school.student.student" defaultMessage="Student" />,
      dataIndex: 'studentEnrollmentId',
      valueType: 'text',
      render: (_, record) => studentLabel(students[record.studentEnrollmentId || '']),
    },
    {
      title: <FormattedMessage id="school.fee.feeMaster" defaultMessage="Fee Master" />,
      dataIndex: 'feeMasterId',
      valueType: 'text',
      render: (_, record) => feeMasterLabel(feeMasters[record.feeMasterId || ''], groups, types),
    },
    {
      title: <FormattedMessage id="school.fee.generatedBy" defaultMessage="Generated By" />,
      dataIndex: 'generatedBy',
      valueType: 'text',
    },
  ];

  return (
    <ReferencePage<V1StudentFee>
      columns={columns}
      create={(fields: V1CreateStudentFeeRequest) =>
        service.studentFeeServiceCreateStudentFee({ body: fields })
      }
      delete={(record) => service.studentFeeServiceDeleteStudentFee({ id: record.id! })}
      get={async (id) => (await service.studentFeeServiceGetStudentFee({ id })).data}
      list={async (req: any) =>
        (await service.studentFeeServiceListStudentFee2({ body: req })).data
      }
      title={(record) =>
        [
          studentLabel(students[record.studentEnrollmentId || '']),
          feeMasterLabel(feeMasters[record.feeMasterId || ''], groups, types),
        ]
          .filter(Boolean)
          .join(' - ') || record.id
      }
      update={(record, fields: any) =>
        service.studentFeeServiceUpdateStudentFee2({
          studentFeeId: record.id!,
          body: { studentFee: { id: record.id!, ...fields } },
        })
      }
      formItems={
        <>
          <ProFormSelect
            name="studentEnrollmentId"
            label={intl.formatMessage({ id: 'school.student.student', defaultMessage: 'Student' })}
            rules={[{ required: true }]}
            request={async ({ keyWords }) => {
              const resp = await studentService.studentServiceListStudent2({
                body: { pageSize: 100, search: keyWords, sort: ['admission_no'] },
              });
              return (resp.data.items || [])
                .filter((item) => item.enrollment?.id)
                .map((item) => ({
                  label: studentLabel(item),
                  value: item.enrollment!.id,
                }));
            }}
            showSearch
          />
          <ProFormSelect
            name="feeMasterId"
            label={intl.formatMessage({ id: 'school.fee.feeMaster', defaultMessage: 'Fee Master' })}
            rules={[{ required: true }]}
            request={async () => {
              const resp = await feeMasterService.feeMasterServiceListFeeMaster2({
                body: { pageSize: 200, sort: ['due_date'] },
              });
              return (resp.data.items || []).map((item) => ({
                label: feeMasterLabel(item, groups, types),
                value: item.id,
              }));
            }}
            showSearch
          />
          <ProFormText
            name="generatedBy"
            label={intl.formatMessage({
              id: 'school.fee.generatedBy',
              defaultMessage: 'Generated By',
            })}
          />
        </>
      }
    />
  );
};

export default TableList;
